name: keeplist_social
description: Cross-platform library for validating and sanitizing social media profile URLs
version: 1.0.0
homepage: https://github.com/keeplist-io/keeplist-social

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  assets:
    - ../patterns/

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
