name: Dart Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'dart/**'
      - 'patterns/**'
      - '.github/workflows/dart.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'dart/**'
      - 'patterns/**'
      - '.github/workflows/dart.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dart

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate pattern sources
        run: dart run ../scripts/build_patterns.dart

      - name: Format generated sources
        run: dart format lib/generated/patterns.dart

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
