name: TypeScript Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'ts/**'
      - 'patterns/**'
      - '.github/workflows/typescript.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ts/**'
      - 'patterns/**'
      - '.github/workflows/typescript.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ts

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: './ts/yarn.lock'

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: --cwd ./ts install # 
        
    - name: Run lint
      uses: borales/actions-yarn@v4
      with:
        cmd: --cwd ./ts lint # 
    - name: Run build
      uses: borales/actions-yarn@v4
      with:
        cmd: --cwd ./ts build # 
    - name: Run test
      uses: borales/actions-yarn@v4
      with:
        cmd: --cwd ./ts test # 
